// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiscoveredTests() {
  return window['go']['main']['App']['GetDiscoveredTests']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunTests() {
  return window['go']['main']['App']['RunTests']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
