// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetDiscoveredTests():Promise<Array<string>>;

export function Quit():Promise<void>;

export function RunTests():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function TogglePause():Promise<boolean>;
